version: "3.9"

services:
  postgres:
    image: postgres:13.4
    hostname: postgres
    restart: unless-stopped
    healthcheck:
      test:
        - "CMD"
        - "sh"
        - "-c"
        - "pg_isready"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_volume

  migration:
    depends_on:
      - postgres
    build:
      context: ./db
    entrypoint:
      - sh
      - -c
      - |
        dockerize -wait tcp://postgres:5432
        migrate \
        -path=/migrations/ \
        -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE} \
        up

volumes:
  postgres_volume:
